### ISSUE TITLE
tüm komutlar bunlar mı?

### ISSUE THREAD

**Issue by sevket-karayilan** [SezerFidanci/TJK-API#1]
merhaba çalışmanız için teşekkür ederiz. tüm komutlar bunlar mı? https://ebayi.tjk.org/s/d/program gibi ve daha fazla komutların oluğu bir döküman var mıdır? misal 1 ata ait yarışları çekmek gibi veya bir ata ait galoplar, bir koşuya ait galoplar gibi vs

**Comment by SezerFidanci** [comment]
merhaba diğer endpoint'leri ebayi.tjk.org adresini tarayıcı üzerinden network dinleyerek yakalayabilirsiniz. bahsetttiğiniz gibi at ve ata ait diğer detay veriler public olarak mevcut.
